apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-micro
spec:
  selector:
    matchLabels:
      app: test-micro
  replicas: 2
  template:
    metadata:
      labels:
        app:test-micro
    spec:
      containers:
      - name: test-micro
        image: malla/test-kube:latest      