# looks same as replica set
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-micro
spec:
  selector:
    matchLabels:
      app: test-kube
  replicas: 2
  template:
    metadata:
      labels:
        app: test-micro
    spec:
      containers:
      - name: test-micro
        image: malla/test-microe:latest